substitutions:
  hostname: controlpanel
  friendly_name: ControlPanel

esphome:
  name: $hostname
  friendly_name: $friendly_name

esp32:
  board: jczn_2432s028r
  framework:
    #type: esp-idf
    type: arduino

# Enable logging
logger:
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  password: ""
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: idLblConnSts
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: idLblConnSts


ota:
  - platform: esphome
    password: ""

wifi:
  networks:
    - ssid: !secret wifi_virus_ssid
      password: !secret wifi_virus_pw
    - ssid: !secret wifi_dombai_ssid
      password: !secret wifi_dombai_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Controlpanel Fallback Hotspot"
    password: !secret fallback_pw

captive_portal:

###################################################################################################
# =================================================================================================
# Hardware related setup
i2c:
  - sda: 27
    scl: 22
    scan: true

spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

###################################################################################################
# === Sensors =====================================================================================
#sensor:
#  - platform: homeassistant
#    id: idHaNappaliTmp
#    entity_id: sensor.nappalisens_nappali_h_m_rs_klet
#    internal: true
#    on_value:
#      - lvgl.indicator.update:
#          id: temperature_needle
#          value: !lambda return x * 10;
#      - lvgl.label.update:
#          id: temperature_text
#          text:
#            format: "%.1f°C"
#            args: [ 'x' ]

# font:
#  - file: "gfonts://Roboto"
#    id: idRoboto10
#    size: 10
#    bpp: 4

# === LVGL ========================================================================================
lvgl:
  top_layer:    
    widgets:
      #---[ footer ]-------------------------------------------------------------------------------
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: header_footer
          rows:
            - buttons:
                - id: page_prev
                  text: "\uF053"
                  on_press:
                    then:
                      lvgl.page.previous: 
                - id: page_home
                  text: "\uF015"
                  on_press:
                    then:
                      lvgl.page.show: idPageLentRdny
                - id: page_next
                  text: "\uF054"
                  on_press:
                    then:
                      lvgl.page.next: 
      #---[ Connection status ]--------------------------------------------------------------------
      - label:
          text: "\uF1EB"
          id: idLblConnSts
          styles: header_footer
          hidden: true
          align: top_right
          x: -2
          y: 7
          text_align: right
          text_color: 0xFFFFFF

  pages:
    - id: idPageLentRdny
      widgets:
        !include Configs/pageLentiRdny.yaml
    - id: idPageKapuGrzs
      widgets:
        !include Configs/pageKapuGrzs.yaml
 

  style_definitions:
    !include Configs/styleDefinitions.yaml




# =================================================================================================
# === Lights =====================================================================================
output:
  - id: backlight_pwm
    platform: ledc
    pin: 21
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: true

light:
  - id: backlight
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - id: led
    platform: rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

# =================================================================================================
# === Display =====================================================================================
# Setup the ili9xxx platform
display:
  - id: idDisplay
    platform: ili9xxx
    model: TFT 2.4R # original used to be LI9341
    #model: st7789v
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number: 2
      ignore_strapping_warning: true
    invert_colors: true # original used to be false
    color_palette: 8BIT # added this line
    update_interval: never
    auto_clear_enabled: false
    transform: # added this line
      swap_xy: true
      mirror_x: false
    dimensions: #added this line
      height: 320
      width: 240
touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      mirror_x: false # original used to be true
      mirror_y: true #added this line
      swap_xy: false #added this line
    #on_touch:
    #  - lambda: |-
    #        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
    #          touch.x,
    #          touch.y,
    #          touch.x_raw,
    #          touch.y_raw
    #        );
