substitutions:
  hostname: controlpanel
  friendly_name: ControlPanel

esphome:
  name: $hostname
  friendly_name: $friendly_name
  # platformio_options:
  #   build_flags: "-DLV_COLOR_16_SWAP=1"

esp32:
  board: jczn_2432s028r
  framework:
    #type: esp-idf
    type: arduino

# Enable logging
logger:
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  password: ""
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: idLblConnSts
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: idLblConnSts

ota:
  - platform: esphome
    password: ""

wifi:
  networks:
    - ssid: !secret wifi_virus_ssid
      password: !secret wifi_virus_pw
    - ssid: !secret wifi_dombai_ssid
      password: !secret wifi_dombai_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Controlpanel Fallback Hotspot"
    password: !secret fallback_pw

captive_portal:

###################################################################################################
# ===[ Globals ]===================================================================================
number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: idDisplayTimeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box

# =================================================================================================
# --- Global variables ----------------------------------------------------------------------------
globals:
  # --- time counter --------------------------------------------------------------------------------
  - id: idGlbTCntr
    type: int
    restore_value: no
    initial_value: "0"
  - id: idLvglIdleFlag
    type: int
    restore_value: no
    initial_value: "0"


# =================================================================================================
# --- Interval ------------------------------------------------------------------------------------
interval:
  # --- 5 sec periodic timer ----------------------------------------------------------------------
  - interval: 1s
    then:
      - lambda: |-          
          if (id(idLvglIdleFlag)) {
             id(idGlbTCntr)++;

             if (5U == id(idGlbTCntr)) {
               lvgl_lvglcomponent_id->show_page(idPagePic1->index, LV_SCR_LOAD_ANIM_NONE, 150);         
             } 
             else if (10U == id(idGlbTCntr)) {
               lvgl_lvglcomponent_id->show_page(idPagePic2->index, LV_SCR_LOAD_ANIM_NONE, 150);         
               id(idGlbTCntr) = 0U;
             }
          }

###################################################################################################
# =================================================================================================
# Hardware related setup
i2c:
  - sda: 27
    scl: 22
    scan: true

spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

###################################################################################################
# === Fonts ======================================================================================
# font:
#   - file: "custom/materialdesignicons-webfont.ttf"
#     id: mdi_42
#     size: 42
#     bpp: 4
#     glyphs: [
#       "\U000F0335", # mdi-lightbulb
#       "\U000F0336", # mdi-lightbulb-outline
#       ]

# === Sensors =====================================================================================
text_sensor:
  - platform: homeassistant
    id: idGarazsKapuState
    entity_id: binary_sensor.garagecontrol_garazsajto
    on_value:
      then:
        # - lvgl.widget.update:
        #     id: idBGarazsKapuLabel
        #     state:
        #       checked: !lambda return (0 == x.compare(std::string{"on"}));
        #       disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: idBGarazsKapuLabel
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "Nyitva";
              } else {
                  icon = "Zarva";
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;

#sensor:
#  - platform: homeassistant
#    id: idHaNappaliTmp
#    entity_id: sensor.nappalisens_nappali_h_m_rs_klet
#    internal: true
#    on_value:
#      - lvgl.indicator.update:
#          id: temperature_needle
#          value: !lambda return x * 10;
#      - lvgl.label.update:
#          id: temperature_text
#          text:
#            format: "%.1f°C"
#            args: [ 'x' ]

# font:
#  - file: "gfonts://Roboto"
#    id: idRoboto10
#    size: 10
#    bpp: 4

# =================================================================================================
# === Outputs =====================================================================================
output:
  - id: idBacklightPwmPin
    platform: ledc
    pin: 21
    frequency: 1000 Hz
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: true

light:
  - id: idBacklight
    platform: monochromatic
    output: idBacklightPwmPin
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - id: idLed
    platform: rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

# === Images ======================================================================================
image:
  - file: "Pic\\tipli_1.jpg"
    id: idPic1
    type: RGB565
    # transparency: opaque
    # dither: NONE
    # invert_alpha: false
    resize: 240x320
  - file: "Pic\\pic_2.jpg"
    id: idPic2
    type: RGB565
    # transparency: opaque
    # dither: NONE
    # invert_alpha: false
    resize: 240x320
# === LVGL ========================================================================================
lvgl:
  top_layer:
    widgets:
      #---[ footer ]-------------------------------------------------------------------------------
      - buttonmatrix:
          align: bottom_mid
          styles: idStyleFooter
          pad_all: 0
          outline_width: 0
          id: idTopLayer
          items:
            styles: idStyleFooter
          rows:
            - buttons:
                - id: page_prev
                  text: "\uF053"
                  on_press:
                    then:
                      - if:
                          condition:
                            - lambda: 'return (lvgl_lvglcomponent_id->get_current_page() == 0);'
                          then:
                            - lambda: 'lvgl_lvglcomponent_id->show_page(idPageLentRdny->index, LV_SCR_LOAD_ANIM_NONE, 500);'
                          else:
                            lvgl.page.previous:                          
                - id: page_home
                  text: "\uF015"
                  on_press:
                    then:
                      lvgl.page.show: idPageKapuGrzs
                - id: page_next
                  text: "\uF054"
                  on_press:
                    then:
                      - if:
                          condition:
                            - lambda: 'return (lvgl_lvglcomponent_id->get_current_page() == 1);'
                          then:
                            - lambda: 'lvgl_lvglcomponent_id->show_page(idPageKapuGrzs->index, LV_SCR_LOAD_ANIM_NONE, 500);'
                          else:
                            lvgl.page.next:                          
                      
      #---[ Connection status ]--------------------------------------------------------------------
      - label:
          text: "Csatlakozva...  \uF1EB"
          id: idLblConnSts
          styles: header
          hidden: true
          align: top_right
          x: -2
          y: 7
          text_align: right
          text_color: 0xFFFFFF
  #---[ Pages ]-----------------------------------------------------------------------------------
  pages:
    - id: idPageKapuGrzs
      styles: idStylePageBack
      widgets: !include Configs/pageKapuGrzs.yaml
    - id: idPageLentRdny
      styles: idStylePageBack
      widgets: !include Configs/pageLentiRdny.yaml    
    - id: idPagePic1
      styles: idStylePageBack
      widgets:
        - image:
            src: idPic1
            # x: 0
            # y: 0
            align: CENTER
    - id: idPagePic2
      styles: idStylePageBack
      widgets:
        - image:
            src: idPic2
            # x: 0
            # y: 0
            align: CENTER

  style_definitions: !include Configs/styleDefinitions.yaml
  #---[ Idle handling ]--------------------------------------------------------------------------
  on_idle:
    timeout: !lambda "return (id(idDisplayTimeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_on:
          id: idBacklight
          brightness: 70%
          transition_length: 500ms
      # - lvgl.pause:
      - lambda: |-
          auto *top = lv_layer_top();
          lv_obj_add_flag(top, LV_OBJ_FLAG_HIDDEN);    // hide     
          lvgl_lvglcomponent_id->show_page(idPagePic1->index, LV_SCR_LOAD_ANIM_NONE, 500);          
          id(idLvglIdleFlag) = 1;     



# =================================================================================================
# === Display =====================================================================================
# Setup the ili9xxx platform
display:
  - id: idDisplay
    platform: ili9xxx
    model: TFT 2.4R # original used to be LI9341
    color_order: RGB
    invert_colors: false
    # color_palette: 8BIT
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number: 2
      ignore_strapping_warning: true
    update_interval: never
    auto_clear_enabled: false
    transform: # added this line
      swap_xy: true
      mirror_x: false
    dimensions: #added this line
      height: 320
      width: 240
# ===[  Touchscreen ]==============================================================================
touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      mirror_x: false # original used to be true
      mirror_y: true #added this line
      swap_xy: false #added this line
    on_release:
      - if:
          # condition: lvgl.is_paused
          condition: 
            lambda: 'return id(idLvglIdleFlag);'
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on:
                id: idBacklight
                brightness: 100%
                transition_length: 500ms                  
            - lambda: |-
                auto *top = lv_layer_top();
                lv_obj_clear_flag(top, LV_OBJ_FLAG_HIDDEN);  // show
                lvgl_lvglcomponent_id->show_page(idPageKapuGrzs->index, LV_SCR_LOAD_ANIM_NONE, 500);
                id(idLvglIdleFlag) = 0;

  # Uncomment to enable touch logging
  #on_touch:
  #  - lambda: |-
  #        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
  #          touch.x,
  #          touch.y,
  #          touch.x_raw,
  #          touch.y_raw
  #        );
